# ---
# title: National Models 5.0 - population estimation
# author: Mannfred Boehm
# created: August 6th, 2024
# ---


#'@param aoi "Area of Interest". Defined and created via Melina's function(s). 
#'
#'@param year A character vector specifying the year(s) to estimate populations from. Data are available at five year intervals starting from 1985, e.g. "1985", "1990",..."2020". 
#'
#'@param version Either "v4" or "v5", indicating which version of the BAM National Models to analyse.
#'
#'@param species The species to be summarised. A `character` with names denoting the species of interest. Names must be of one type: common, scientific, or four letter bird codes.   
#' This argument needs to be integrated with `sppList()`
#' 
#'@param type Optional. Indicate the type of names being used; one of "species_code" (FLBC), "commonName", or "scientificName". If left blank, the function will attempt to identify the type.
#'
#'
#'@return A population estimate (or estimates) of the mean and standard deviation density of males per hectare. 
#'
#'
#'@importFrom googledrive drive_ls drive_get drive_download drive_auth
#'@importFrom dplyr
#'
#'@examples ...tbd


library(terra)
library(dplyr)
library(googledrive)

# NOTE: this script is being developed around test layers generated by Melina's `BAMexploreR::getlayerNM` function

devtools::load_all(path="C:/Users/mannf/Proton Drive/mannfredboehm/My files/Drive/BAMexploreR")
googledrive::drive_auth(scopes = "https://www.googleapis.com/auth/drive.readonly")

# connect to BAM Drive to use an example raster (simulating a masked raster that would come out of Melina's function)
#root <- "G:/Shared drives/BAM_NationalModels5"
#test <- terra::rast(x=file.path(root, "output", "mosaics", "extrapolation", "BAWW_8_2020.tiff"))

# since the resolution of the raster is 1000×1000 meters, each cell represents 1,000,000 square meters (1 km2).
test <- BAMexploreR::getlayerNM(spList="BAOR", version="v4", layer="mean", destfile="C:/Users/mannf/Downloads")


bamexplorer_pop <- function(raster, version){
  
  # CHANGE TO n=3 when averaged rasters are available, and consider downstream effects on this function
  # split file name into 4 labels: species, bcr, bootstrap (won't be included in averaged rasters), year
  raster_labels <- stringr::str_split_fixed(files, "-", n=4)
    
  # get values per raster cell then sum across all cells
  # multiply pixel values (#birds) by 100 ha/pixel to give X bird*ha per pixel
  popperpixel <-     terra::values(raster[[1]])*100 
  sum(popperpixel, na.rm = TRUE)

  
  } # close loop

  results <- tibble(species = species, population_estimate = )
  return(results)
  
} # close function


  

  
  
  
  
  
  
  